name: sync

on:
  push:
    branches:    
      - main

jobs:
  midsearch:
    name: midsearch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: pip install git+https://github.com/gorse-io/midsearch.git
